language: rust
install:
- wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.16.tar.gz
- tar xvfz libsodium-1.0.16.tar.gz
- cd libsodium-1.0.16 && ./configure --prefix=/usr && make && sudo make install && cd ..
script:
- cargo build --verbose
- cargo test --verbose
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
    - rust: beta
